from pyspark import pipelines as dp
from pyspark.sql import functions as F

# =============================================================================
# Generic Bronze Ingestion Pipeline
# =============================================================================
# Ingests JSON files from Volumes (generated by synthetic_setupdata_generation)
# into streaming tables in catalog catadb360dev.
#
# Pipeline Parameters (set in pipeline configuration):
#   group_code  - Integer. Fetches table list from control table. Takes precedence.
#   table_name  - Comma-separated list of table names (one or more).
#
# Validation:
#   - At least one of group_code or table_name must be provided.
#   - group_code must be a single integer value.
#   - group_code takes precedence over table_name when both are provided.
# =============================================================================

# --- Constants ---
VOLUME_NAME = "data_streaming_files"
CONTROL_TABLE = "catadb360dev.utilities.job_control_info"


# --- Read pipeline parameters ---
group_code_param = spark.conf.get("group_code", "")
table_name_param = spark.conf.get("table_name", "")

# --- Parameter Validation ---
if not group_code_param and not table_name_param:
    raise ValueError(
        "At least one of 'group_code' or 'table_name' pipeline parameter must be provided."
    )

group_code = None
if group_code_param:
    # Ensure only one value (no commas)
    if "," in group_code_param:
        raise ValueError(
            f"Only one 'group_code' value is allowed. Got: '{group_code_param}'"
        )
    # Validate it is an integer
    try:
        group_code = int(group_code_param.strip())
    except ValueError:
        raise ValueError(
            f"'group_code' must be an integer value. Got: '{group_code_param}'"
        )

# --- Resolve table list ---
tables_to_ingest = []  # list of (table_name, catalog, schema) tuples

if group_code is not None:
    # group_code takes precedence: fetch table list from control table
    control_rows = (
        spark.read.table(CONTROL_TABLE)
        .filter(F.col("group_code") == group_code)
        .orderBy("seq_num")
        .select("table_name", "catalog", "schema")
        .collect()
    )
    if not control_rows:
        raise ValueError(
            f"No tables found in control table for group_code={group_code}"
        )
    tables_to_ingest = [(row.table_name, row.catalog, row.schema) for row in control_rows]
else:
    # Use provided table_name list
    table_names = [t.strip() for t in table_name_param.split(",") if t.strip()]
    if not table_names:
        raise ValueError("'table_name' parameter is empty or contains only whitespace.")

    # Lookup catalog and schema from control table for each table
    control_rows = (
        spark.read.table(CONTROL_TABLE)
        .filter(F.col("table_name").isin(table_names))
        .select("table_name", "catalog", "schema")
        .collect()
    )
    found_map = {row.table_name: (row.catalog, row.schema) for row in control_rows}
    missing = [t for t in table_names if t not in found_map]
    if missing:
        raise ValueError(
            f"Tables not found in control table: {missing}"
        )
    tables_to_ingest = [(name, found_map[name][0], found_map[name][1]) for name in table_names]

# --- Create streaming tables and append flows dynamically ---
for tbl_name, tbl_catalog, tbl_schema in tables_to_ingest:
    volume_path = f"/Volumes/{tbl_catalog}/{tbl_schema}/{VOLUME_NAME}/{tbl_name}"
    target_table = f"{tbl_catalog}.{tbl_schema}.{tbl_name}_bronze"

    # Create the target streaming table
    dp.create_streaming_table(name=target_table)

    # Define append flow with Auto Loader ingestion
    @dp.append_flow(target=target_table, name=f"ingest_{tbl_name}")
    def create_flow(path=volume_path):
        return (
            spark.readStream.format("cloudFiles")
            .option("cloudFiles.format", "json")
            .option("cloudFiles.inferColumnTypes", "true")
            .load(path)
        )
